"""Add project document section models

Revision ID: ce92af15d062
Revises: 001_initial
Create Date: 2026-01-21 14:25:37.349671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce92af15d062'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('requirements', 'functional', 'specification', 'rom', 'custom', name='documenttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'approved', 'superseded', name='documentstatus'), nullable=False),
    sa.Column('derived_from_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('liveblocks_room_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('last_edited_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['derived_from_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['last_edited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'gatherer', 'client', 'viewer', name='projectrole'), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('diff_from_previous', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('empty', 'draft', 'needs_review', 'approved', 'disputed', name='sectionstatus'), nullable=False),
    sa.Column('prosemirror_node_id', sa.String(length=100), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('open_questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_bindings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('binding_type', sa.Enum('discussion', 'editing', 'reference', 'question', 'approval', name='bindingtype'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('media', 'extracted_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('media', 'transcript',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('sessions', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.add_column('sessions', sa.Column('active_document_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'documents', ['active_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'active_document_id')
    op.drop_column('sessions', 'project_id')
    op.alter_column('media', 'transcript',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('media', 'extracted_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('section_bindings')
    op.drop_table('sections')
    op.drop_table('document_versions')
    op.drop_table('project_members')
    op.drop_table('documents')
    op.drop_table('projects')
    # ### end Alembic commands ###
